## Implementation of Naive Bayes using Scikit Learn 
#### MCA404B Machine Learning
#### Instructor: Tejmani Sinam, Manipur University, Dated 07-06-2022 


In [1]:
#Import the necessary Python modules

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Import the Scikit Learn ML Libraries

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris

In [5]:
# Read in the data using Scikit Learn function load_iris()

In [7]:
X, y = load_iris(return_X_y=True)
#print(df.head())

In [9]:
# Split the Labelled data set into Training and Testing sets

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4)

In [11]:
# Instansiate a Logistic Regression Object and Train the model
# using the training data set

In [12]:
NB = GaussianNB()
NB.fit(X_train, y_train)

GaussianNB()

In [13]:
# Predict the Testing data set

In [14]:
y_pred = NB.predict(X_test)

In [15]:
# Print the Results: Theta values, Confusion Matrix, Accuracy, Precision, Recall and F1-Score

In [16]:
confusion_matrix1 = confusion_matrix(y_test, y_pred)
print()
print("Confusion Matrics")
print(confusion_matrix1)

result = classification_report(y_test,y_pred)
print()
print("Classification Results")
print(result)


Confusion Matrics
[[18  0  0]
 [ 0  8  0]
 [ 0  1 11]]

Classification Results
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.89      1.00      0.94         8
           2       1.00      0.92      0.96        12

    accuracy                           0.97        38
   macro avg       0.96      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38

